### ISSUE TITLE
adjoint sensitivity method questions

### ISSUE THREAD

**Issue by Seunghyeon-Cho** [a-norcliffe/sonode#1]
Hi,

Thanks for the great work which targets a real issue of Neural ODE.
I wonder if SONODE's forward expression and background expression are composed in the same way. (For example, in the case of the HBNODE paper, the next version of SONODE, it is constructed in the same way.)

Thanks.

**Comment by a-norcliffe** [comment]
Hi,

Thank you for the question! HBNODEs have very specific structure in their second order ode. As a result the adjoint equation has the same structure. SONODEs do not have any specific structure, we looked at a general second order differential equation. Therefore the adjoint ode does not have any specific structure either. It "has the same structure" if you say that it is a second order ode, because that was the only property that is enforced by SONODEs.

If we take the general result for the adjoint ode in (eq 5 of SONODEs), and apply it to HBNODEs ode (eq 9 of HBNODEs) then we recover the adjoint ode for HBNODEs (eq 11 of HBNODEs).

Hope that helps!

**Comment by Seunghyeon-Cho** [comment]
Thanks a lot for the clarification, @a-norcliffe 

A small additional Question :
Can you theoretically prove that SONODE is faster than vanilla NODE? 
Or the reason for that (For example, the faster computation of the gradients in SONODE model.)

Thanks.

**Comment by a-norcliffe** [comment]
No problem!

It's actually the other way round, the second order version of the adjoint is slower than the coupled first order. In Appendix B this is all derived. The main point is at the end of Appendix B where we show there are two ways to represent the adjoint, one is purely second order and one is a coupled first order system.

The coupled first order system is an entangled version of the second order, and requires fewer operations per function evaluation, and is therefore theoretically faster. Entangled dynamics is a constant theme of the paper, we show that ANODEs can learn second order behaviour in an entangled way. This means they can learn it more efficiently but often at the cost of interpretability. The entangled behaviour is useful in the adjoint backpropagation because we only care about speed, not interpretability.
