### ISSUE TITLE
Assertion error t

### ISSUE THREAD

**Issue by cadop** [a-norcliffe/sonode#2]
When running the 2D function scripts I get an assertion error for torchdiffeq that t must be 1 dimensional timelike.  

https://github.com/a-norcliffe/sonode/blob/master/experiments/function_fitting/2d_function/2d_function_fit_anode_given_init_conditions.py

Is there another library that it should be calling instead?

**Comment by a-norcliffe** [comment]
Hi thank you for raising the issue. Unfortunately this is quite old code that isn't maintained, it used to work for me but also has given some errors. I believe I have fixed the issue.

**Comment by cadop** [comment]
Thanks, it seems to work, but this line https://github.com/a-norcliffe/sonode/blob/be19ef01ce449159ca8f72d6bb92a6493db1f167/experiments/function_fitting/2d_function/2d_function_fit_anode_given_init_conditions.py#L204 I think should be commented out, the plot fails because its shape 1, but `plot_ts` seems to be the correct size. 

Also the corresponding sonode script fails https://github.com/a-norcliffe/sonode/blob/master/experiments/function_fitting/2d_function/2d_function_fit_sonode_given_init_conditions.py 

But also I was wondering, is there a reason its not maintained?  For 2D functions do you think there are newer/better libraries out there now, or you have just moved on?

Thanks for sharing the code

**Comment by a-norcliffe** [comment]
Hi, feel free to comment out the line, this is quite old, it worked when I ran it two years ago, but I appreciate there may be errors. The corresponding script likely requires similar fixes to run.

The reason this is not maintained is because this is research code used almost exclusively by this small team two years ago. I was quite inexperienced at the time, and this shows in the code. I may use time one weekend to rewrite a lot of this, hopefully you agree the experiments are generally quite simple (demonstrating some effects) and so it should not be too hard for someone to write their own.

**Comment by cadop** [comment]
Thanks for the quick response.  Yes naturally I commented out that line and it worked, so I was just suggesting as a fix.  But, I see you are probably focused on other things.  I think it may be useful to update the readme to just state that its not being maintained anymore and if people have fixes they can make a pull request (if you even want to deal with that). 

Yes experiments are simple enough, its just nice to be able to run the repo directly to see paper results, otherwise maybe I make an index slice error and get horrible results that aren't accurate to what it should have been. Really I was just curious because it was hard to find 2D functions for node on github.

**Comment by a-norcliffe** [comment]
Hi, I totally agree with you, I will update the readme, and will try to find time to fix the repo to be easier to run.
